#updated version
logo: assets/logo.jpg # Ensure this path is correct
theme: minima
skin: dark # Minima theme settings
title: Personal blog - Where all my ideas go to play
author: Cam3lnet
description: Welcome to my GitHub Pages site.
url: "https://cam3lnet.github.io/skills-github-pages/" # Your website URL
social:
  github: Cam3lnet

highlighter: rouge  # Syntax highlighter
markdown: kramdown # Markdown parser
plugins:
  - jekyll-feed
  - jekyll-seo-tag

