theme: minima
skin: dark # Minima theme settings
title: Personal blog - Where all my ideas go to play
author: Cam3lnet
description: >- # this means to ignore newlines until "baseurl:"
              Welcome to my GitHub Pages site.
logo: /assets/logo.png
